runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:MA78dxECE38/faPZerIwOjCqO4Lw/cm68Q9HwUpcuYA=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie